# general
gpu_id: 2
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
dataset_save_path: ~
save_dataloaders: False
dataloaders_save_path: ~
log_wandb: False
wandb_project: 'recbole'

# training settings
epochs: 300
train_batch_size: 256
learner: adam
learning_rate: 0.001


ULRec: Yes
alpha: 0.9

#train_neg_sample_args: ~

## Seq
#neg_sampling: ~
##   uniform: 1

# non-Seq
neg_sampling:
   uniform: 1

# layers
n_layers: 2
Tau: 0.2

eval_step: 1
stopping_step: 10
clip_grad_norm: ~
# clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.0
loss_decimal_place: 4
require_pow: False

# evaluation settings
eval_args: 
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full
repeatable: False
# metrics: ["Recall","MRR","NDCG","Hit","Precision"]
metrics: ["Recall","MRR","NDCG"]
topk: [5,10,20]
valid_metric: MRR@10
valid_metric_bigger: True
eval_batch_size: 4096
metric_decimal_place: 4